version: '3'
services:
  app:
    build: .
    ports:
      - "5500:5500"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
      - NET_RAW