version: '3.8'

services:
  api:
    build: .
    container_name: network-ids-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app  
      - ./models:/app/app/models 
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - MODEL_PATH=/app/app/models/model.pkl
      - IDLE_THRESHOLD=500000
      - PREDICTION_THRESHOLD=0.5
